apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: backend
spec:
  namespaceSelector:
    matchNames:
      - backend
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: frontend
spec:
  namespaceSelector:
    matchNames:
      - frontend
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
