{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | default "internet-facing" | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType | default "ip" | quote }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName | default "cloudflux-alb" | quote }}
    alb.ingress.kubernetes.io/group.order: "10"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: {{ .Values.ingress.className | default "alb" }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: {{ .Values.service.port }}
{{- end }}
