clusterName: cloudflux-prod
region: ap-south-1
vpcId: REPLACE_WITH_VPC_ID
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cloudflux-prod-aws-lb-controller
